// export const themes = [
//   'Argonaut',
//   'Atom',
//   'Aura',
//   'Ayu',
//   'Blue Matrix',
//   'Bright Lights',
//   'Challenger Deep',
//   'Cyberpunk',
//   'Dracula Plus',
//   'Fahrenheit',
//   'Fish Tank',
//   'Flatland',
//   'Hardcore',
//   'Kolorit',
//   'Laserwave',
//   'Lovelace',
//   'Monokai Vivid',
//   'Mono Red',
//   'Palenight',
//   'Panda',
//   'Paraiso Dark',
//   'Pixie Floss',
//   'Rebecca',
//   'Thayer Bright',
//   'The Hulk',
//   'Tomorrow Night',
//   'Twilight',
//   'Ultra Violent',
//   'Vaughn',
// ]

export { default as themesJson } from '../themes/_all.json'
